# Generated by Django 5.1.15 on 2026-04-29 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Linux', 'Linux'), ('Shell Scripting', 'Shell Scripting'), ('AWS', 'AWS'), ('Jenkins', 'Jenkins'), ('Git & GitHub', 'Git & GitHub'), ('Docker', 'Docker'), ('Kubernetes', 'Kubernetes'), ('Ansible', 'Ansible')], max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='course_covers/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='catalog_cou_categor_ba0f59_idx'), models.Index(fields=['slug'], name='catalog_cou_slug_db19fe_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order_index', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='catalog.course')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('course', 'order_index')},
            },
        ),
        migrations.CreateModel(
            name='CourseLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order_index', models.PositiveIntegerField()),
                ('video_file', models.FileField(blank=True, null=True, upload_to='course_videos/')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='catalog.coursemodule')),
            ],
            options={
                'ordering': ['order_index'],
                'unique_together': {('module', 'order_index')},
            },
        ),
    ]
